name: Release all major versions on Dockerhub

on:
  push:
    branches:
      - develop
      - release/*
    paths:
      - ".github/workflows/dockerhub-release-matrix.yml"
      - "ansible/vars.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    outputs:
      build_args: ${{ steps.args.outputs.result }}
    steps:
      - name: Checkout Repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.29.1/install
          extra_nix_config: |
            substituters = https://cache.nixos.org https://nix-postgres-artifacts.s3.amazonaws.com
            trusted-public-keys = nix-postgres-artifacts:dGZlQOvKcNEjvT7QEAJbcV6b6uk7VF/hWMjhYleiaLI=% cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Set PostgreSQL version environment variable
        run: echo "POSTGRES_MAJOR_VERSION=17" >> $GITHUB_ENV
      
      - id: args
        run: |
          nix run nixpkgs#nushell -- -c '
            open ansible/vars.yml 
            | items { |key value| {name: $key, item: $value} } 
            | where { |it| ($it.item | describe) == "string" } 
            | each { |it| $"($it.name)=($it.item)" } 
            | str join "\n" 
            | save --append $env.GITHUB_OUTPUT
          '    
  build_release_image:
    needs: [build]
    strategy:
      matrix:
        postgres: ${{ fromJson(needs.prepare.outputs.matrix_config).include }}
        arch: [amd64, arm64]
    runs-on: ${{ matrix.arch == 'amd64' && 'self-hosted' || 'large-linux-arm' }}
    timeout-minutes: 180
    steps:
      - name: Checkout Repo
        uses: supabase/postgres/.github/actions/shared-checkout@HEAD
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.29.1/install
          extra_nix_config: |
            substituters = https://cache.nixos.org https://nix-postgres-artifacts.s3.amazonaws.com
            trusted-public-keys = nix-postgres-artifacts:dGZlQOvKcNEjvT7QEAJbcV6b6uk7VF/hWMjhYleiaLI=% cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get image tag
        id: image
        run: |
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            pg_version=$(nix run nixpkgs#nushell -- -c '
              let version = "${{ matrix.postgres.version }}"
              let release_key = if ($version | str contains "orioledb") {
                $"postgresorioledb-17"
              } else {
                $"postgres($version)"
              }
              open ansible/vars.yml | get postgres_release | get $release_key | str trim
            ')
            echo "pg_version=supabase/postgres:$pg_version" >> $GITHUB_OUTPUT
          else
            pg_version=$(nix run nixpkgs#nushell -- -c '
              let version = "${{ matrix.postgres.version }}"
              let release_key = if ($version | str contains "orioledb") {
                $"postgresorioledb-17"
              } else {
                $"postgres($version)"
              }
              open ansible/vars.yml | get postgres_release | get $release_key | str trim
            ')
            echo "pg_version=supabase/postgres:$pg_version" >> $GITHUB_OUTPUT
          fi
      - id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            ${{ needs.build.outputs.build_args }}
          target: production
          tags: ${{ steps.image.outputs.pg_version }}_${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=${{ github.ref_name }}-latest-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-latest-${{ matrix.arch }}
          file: ${{ matrix.postgres.dockerfile }}
